package codingtest.tui.com.fragmenttestproject;

import android.app.Fragment;
import android.content.Context;
import android.net.Uri;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;

import com.google.android.gms.plus.PlusOneButton;

public class PlusOneFragment extends Fragment {

    private OnFragmentInteractionListener mListener;
    private Button button;
    private Button button2;

    private View.OnClickListener onClickListener = new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            switch (view.getId()){
                case R.id.plus_one_button:
                    onButtonPressed("this is a text generated by the button");
                    break;
                case R.id.plus_two_button:
                    onButtonPressed("this is a text generated by the second button");
                    break;
                default:
                    break;
            }
        }
    };

    public PlusOneFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_plus_one, container, false);
        button = view.findViewById(R.id.plus_one_button);
        button.setOnClickListener(onClickListener);
        button2 = view.findViewById(R.id.plus_two_button);
        button2.setOnClickListener(onClickListener);
        return view;
    }

    @Override
    public void onResume() {
        super.onResume();
    }


    public void onButtonPressed(String string) {
        if (mListener != null) {
            mListener.onFragmentInteraction(string);
        }
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnFragmentInteractionListener) {
            mListener = (OnFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    public interface OnFragmentInteractionListener {
        void onFragmentInteraction(String text);
    }

}
